/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graficos;

import Entidades.Enlace_Torneo_Equipos;
import Entidades.Entrenadores;
import Entidades.Equipos;
import Entidades.Jugadores;
import Entidades.Torneos;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Interfaz_Info extends javax.swing.JFrame {
    
    DefaultListModel <String> ListModel = new DefaultListModel <>();// esto es para poder usar la jlist1

    /**
     * Creates new form Interfaz_Info
     */
    public Interfaz_Info() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        _Mostrar_Entrenadores_ = new javax.swing.JButton();
        _Mostrar_Equipos_ = new javax.swing.JButton();
        _Mostrar_Jugadores_ = new javax.swing.JButton();
        _Mostrar_Torneo_ = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        _Mostrar_Enlace1_ = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jList1);

        jButton1.setText("Atras");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Ver Entrenadores");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Ver Equipos");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Ver Jugadores");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Ver Torneso");

        _Mostrar_Entrenadores_.setText("Mostrar");
        _Mostrar_Entrenadores_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _Mostrar_Entrenadores_ActionPerformed(evt);
            }
        });

        _Mostrar_Equipos_.setText("Mostrar");
        _Mostrar_Equipos_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _Mostrar_Equipos_ActionPerformed(evt);
            }
        });

        _Mostrar_Jugadores_.setText("Mostrar");
        _Mostrar_Jugadores_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _Mostrar_Jugadores_ActionPerformed(evt);
            }
        });

        _Mostrar_Torneo_.setText("Mostrar");
        _Mostrar_Torneo_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _Mostrar_Torneo_ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("Ver Enlaces Equipo a Torneo");

        _Mostrar_Enlace1_.setText("Mostrar");
        _Mostrar_Enlace1_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _Mostrar_Enlace1_ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Ver la Informacion que puede crear el Administrador");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("jLabel7");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 153));
        jLabel8.setText("Ver Enlaces Entrenador a Equipo ");

        jButton7.setText("Mostrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(_Mostrar_Enlace1_)
                                            .addComponent(_Mostrar_Torneo_)
                                            .addComponent(_Mostrar_Jugadores_)
                                            .addComponent(_Mostrar_Equipos_)
                                            .addComponent(_Mostrar_Entrenadores_)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(45, 45, 45)
                                        .addComponent(jButton7)))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(4, 4, 4)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(_Mostrar_Entrenadores_))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(_Mostrar_Equipos_))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(_Mostrar_Jugadores_))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(_Mostrar_Torneo_))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(_Mostrar_Enlace1_))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jButton7)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _Mostrar_Entrenadores_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__Mostrar_Entrenadores_ActionPerformed
        jLabel7.setText("Informacion de Entrenadores");
        imprimirEntrenadores();
    }//GEN-LAST:event__Mostrar_Entrenadores_ActionPerformed

    private void _Mostrar_Equipos_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__Mostrar_Equipos_ActionPerformed
       jLabel7.setText("Informacion de Equipos");
       imprimirEquipos();
    }//GEN-LAST:event__Mostrar_Equipos_ActionPerformed

    private void _Mostrar_Jugadores_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__Mostrar_Jugadores_ActionPerformed
        jLabel7.setText("Informacion de Jugadores");
        imprimirJugadores();
    }//GEN-LAST:event__Mostrar_Jugadores_ActionPerformed

    private void _Mostrar_Torneo_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__Mostrar_Torneo_ActionPerformed
        jLabel7.setText("Informacion de Torneo");
        imprimirTorneo();                         
    }//GEN-LAST:event__Mostrar_Torneo_ActionPerformed

    private void _Mostrar_Enlace1_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__Mostrar_Enlace1_ActionPerformed
        jLabel7.setText("Informacion de enlace Equipo/Torneo");
        imprimirEnlace1(); 
    }//GEN-LAST:event__Mostrar_Enlace1_ActionPerformed

    
   public void imprimirEnlace1()  
    {
        ListModel.clear();
        if (Interfaz_Login.metE.inicio==null)
        {
            JOptionPane.showMessageDialog(null, "Lista Vacia");
        }
        
        else
        {          
            Torneos torneo = Interfaz_Login.metT.inicio;    // entro a los Torneo
            while(  torneo != null)
            { 
              Equipos equipo = Interfaz_Login.metE.inicio;
              if(equipo==null)
              {
                JOptionPane.showMessageDialog(null,"Lista de equipos esta vacia");
                break;
              }
              else
              {
 
                while(equipo != Interfaz_Login.metE.fin)
                {
                    Enlace_Torneo_Equipos  enlace =equipo.sigSub;
                    while(enlace != null)
                    {
                        if(enlace.sigTorneo==torneo)
                        {
                            ListModel.addElement("Torneo: "+torneo.nombre +"  se enlazo con "+"Equipo:  "+equipo.nombre);
                            break;
                        }

                    }
                    equipo=equipo.sig;
                }
                if(Interfaz_Login.metE.fin.sigSub.sigTorneo==torneo)
                {
                    ListModel.addElement("Torneo: "+torneo.nombre +"   se enlazo con   "+"Equipo:  "+equipo.nombre);
                    break;
                }
                
              }
              torneo=torneo.sig;
            }
            jList1.setModel(ListModel); 
        }
    } 
    
    public void imprimirTorneo(){
        
        Torneos temp =Interfaz_Login.metT.inicio;
        ListModel.clear();
        while(temp != null)
        {
        ListModel.addElement("Nombre:  "+temp.nombre);// muestra en ListModel el nombre y la edad del Cliente
        temp=temp.sig;
        }
        jList1.setModel(ListModel);    
    }
    
    public void imprimirEntrenadores()
    {
        ListModel.clear();
        if (Interfaz_Login.metEn.inicio==Interfaz_Login.metEn.inicio.sig)
        {
          ListModel.addElement("Nombre: "+Interfaz_Login.metEn.inicio.getNombre() +"  Identificacion: "+ Interfaz_Login.metEn.inicio.getId());// muestra en ListModel el nombre y la edad del Cliente
        }
        else
        {
            Entrenadores temp = Interfaz_Login.metEn.inicio;
            Entrenadores  aux = Interfaz_Login.metEn.inicio;
            while(aux.sig != temp)
            {
                ListModel.addElement("Nombre: "+aux.getNombre() +"  Identificacion:  "+ aux.getId());// muestra en ListModel el nombre y la edad del Cliente
                aux=aux.sig;
            }
            ListModel.addElement("Nombre: "+aux.getNombre()+"  Identificacon:  "+ aux.getId());
        }
        jList1.setModel(ListModel);
        
    }
    
     public void imprimirEquipos()
    {
        ListModel.clear();
        if (Interfaz_Login.metE.inicio==Interfaz_Login.metE.inicio.sig)
        {
          ListModel.addElement("Nombre:  "+ Interfaz_Login.metE.inicio.nombre +"  Codigo:   "+ Interfaz_Login.metE.inicio.codigo);// muestra en ListModel el nombre y la edad del Cliente
        }
        else
        {
            Equipos temp = Interfaz_Login.metE.inicio;
            Equipos aux = Interfaz_Login.metE.inicio;
            while(aux.sig != temp)
            {
                ListModel.addElement("Nombre: "+aux.nombre +"  Codigo:  "+ aux.codigo);// muestra en ListModel el nombre y la edad del Cliente
                aux=aux.sig;
            }
            ListModel.addElement("Nombre: "+aux.nombre +"  Codigo:  "+ aux.codigo);
        }
        jList1.setModel(ListModel);    
    }
     
    public void imprimirJugadores(){
        
        Jugadores temp = Interfaz_Login.metJ.inicio;
        ListModel.clear();
        while(temp != null)
        {
        ListModel.addElement("  Nombre :"+ temp.getNombre()+" Cedula: "+temp.getCedula() +"  Posicion:  "+ temp.getPosicion()+"   Valor: "+temp.getValor()+"$");// muestra en ListModel el nombre y la edad del Cliente
        temp=temp.sig;
        }
        jList1.setModel(ListModel);    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _Mostrar_Enlace1_;
    private javax.swing.JButton _Mostrar_Entrenadores_;
    private javax.swing.JButton _Mostrar_Equipos_;
    private javax.swing.JButton _Mostrar_Jugadores_;
    private javax.swing.JButton _Mostrar_Torneo_;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
