/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graficos;
import java.io.File;
import javax.swing.*;
import Entidades.*;
import Metodos.*;
/**
 *
 * @author Oscar
 */
public class Interfaz_Equipos extends javax.swing.JFrame {
    
    JFileChooser seleccionado = new JFileChooser();
    File archivo;
    byte[] bytesImg;
    
    Gestion_de_Imagenes gestionCasa = new Gestion_de_Imagenes();
    Gestion_de_Imagenes gestionVisita = new Gestion_de_Imagenes();
    
    //MetodosEquipos met =new MetodosEquipos();
    DefaultListModel <String> ListModel = new DefaultListModel <>();// esto es para poder usar la jlist1
    /**
     * Creates new form JFGestionA
     */
    public Interfaz_Equipos() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1_Uniforme_Casa_ = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1_Uniforme_Visita = new javax.swing.JButton();
        lblImagen2 = new javax.swing.JLabel();
        lblImagen1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1_Insertar_Inicio = new javax.swing.JButton();
        jButton2_Insertar_Final = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1_Mostrar_informacion_ = new javax.swing.JButton();
        jButton1_Atras_ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador crea Equipo");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Agregar Equipo");

        jLabel2.setText("Nombre");

        jLabel3.setText("Codigo");

        jLabel4.setText("Uniforme Casa");

        jLabel5.setText("Uniforme Visita");

        jButton1_Uniforme_Casa_.setText("Seleccionar");
        jButton1_Uniforme_Casa_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_Uniforme_Casa_ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("Uniforme Casa");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setText("Uniforme Visita");

        jButton1_Uniforme_Visita.setText("Seleccionar");
        jButton1_Uniforme_Visita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_Uniforme_VisitaActionPerformed(evt);
            }
        });

        lblImagen2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblImagen1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1_Insertar_Inicio.setText("Agragrgar al Inicio");
        jButton1_Insertar_Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_Insertar_InicioActionPerformed(evt);
            }
        });

        jButton2_Insertar_Final.setText("Agrgar al Final");
        jButton2_Insertar_Final.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_Insertar_FinalActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 153));
        jLabel8.setText("Mostrar ");

        jScrollPane1.setViewportView(jList1);

        jButton1_Mostrar_informacion_.setText("Mostrar");
        jButton1_Mostrar_informacion_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_Mostrar_informacion_ActionPerformed(evt);
            }
        });

        jButton1_Atras_.setText("Atras");
        jButton1_Atras_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_Atras_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1_Uniforme_Visita))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1_Uniforme_Casa_)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(jTextField2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1_Insertar_Inicio)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2_Insertar_Final)))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1_Mostrar_informacion_))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(lblImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(lblImagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                        .addComponent(jButton1_Atras_)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jButton1_Uniforme_Casa_))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jButton1_Uniforme_Visita))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1_Insertar_Inicio)
                            .addComponent(jButton2_Insertar_Final)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jButton1_Atras_))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton1_Mostrar_informacion_)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //verifcar como mandar los parametros de las imagenes 
    
    //String insertar=Interfaz_MenuPrincipal.metE.InsertarInicio("a", 1,null,null);
    //String nuevo1=Interfaz_MenuPrincipal.metE.InsertarInicio("Costa Rica", 0, null, null);
    //String nuevo2=Interfaz_MenuPrincipal.metE.InsertarInicio("Estados Unidos", 1, null, null);
    //String nuevo3=Interfaz_MenuPrincipal.metE.InsertarInicio("Honduras", 2, null, null);
    //String nuevo4=Interfaz_MenuPrincipal.metE.InsertarInicio("Mexico", 3, null, null);
    
    private void jButton1_Uniforme_Casa_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_Uniforme_Casa_ActionPerformed
        if(seleccionado.showDialog(null, "ABRIR ARCHIVO") == JFileChooser.APPROVE_OPTION){
            archivo = seleccionado.getSelectedFile();
            
            if(archivo.getName().endsWith("jpg")||archivo.getName().endsWith("png")||archivo.getName().endsWith("gif"))
            {
                bytesImg = gestionCasa.AbrirAImagen(archivo);
                lblImagen1.setIcon(new ImageIcon(bytesImg));
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Por favor seleccione un archivo de texto o de imagen.");
            }
                
            
        }
    }//GEN-LAST:event_jButton1_Uniforme_Casa_ActionPerformed

    private void jButton1_Uniforme_VisitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_Uniforme_VisitaActionPerformed
        if(seleccionado.showDialog(null, "ABRIR ARCHIVO") == JFileChooser.APPROVE_OPTION){
            archivo = seleccionado.getSelectedFile();
            
            if(archivo.getName().endsWith("jpg")||archivo.getName().endsWith("png")||archivo.getName().endsWith("gif"))
            {
                bytesImg = gestionVisita.AbrirAImagen(archivo);
                lblImagen2.setIcon(new ImageIcon(bytesImg));
              
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Por favor seleccione un archivo de texto o de imagen.");
            }
        }
    }//GEN-LAST:event_jButton1_Uniforme_VisitaActionPerformed

    private void jButton1_Insertar_InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_Insertar_InicioActionPerformed
        try 
        {
            
            String nombre=jTextField1.getText();
            int    codigo=Integer.parseInt(jTextField2.getText());
            
            ImageIcon ImagenCasa=(ImageIcon) lblImagen1.getIcon();
            ImageIcon ImagenVisita=(ImageIcon) lblImagen2.getIcon();
            
            if (ImagenCasa != null || ImagenVisita != null)
            {
                boolean verifica=Interfaz_Login.metE.verificaCodigo(codigo);
                if(verifica==false)
                {
                    String insertar=Interfaz_Login.metE.InsertarInicio(nombre, codigo, ImagenCasa, ImagenVisita);

                    JOptionPane.showMessageDialog(null, insertar);
                    //limpiar
                    jTextField1.setText("");
                    jTextField2.setText("");
                    lblImagen1.setText("");
                    lblImagen2.setText("");
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"El codigo seleccionado se encuentra ocupado");
                }
            }
            else
            {
            JOptionPane.showMessageDialog(null,"Debe Seleccionar los Uniformes");
            }
            
        }
        catch (Exception e) 
        {
           JOptionPane.showMessageDialog(null,"Error al Ingresar los Datos");
        }
    }//GEN-LAST:event_jButton1_Insertar_InicioActionPerformed

    private void jButton2_Insertar_FinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_Insertar_FinalActionPerformed
      try 
        {
            
            String nombre=jTextField1.getText();
            int    codigo=Integer.parseInt(jTextField2.getText());
            
            ImageIcon ImagenCasa=(ImageIcon) lblImagen1.getIcon();
            ImageIcon ImagenVisita=(ImageIcon) lblImagen2.getIcon();
            
            if (ImagenCasa != null || ImagenVisita != null)
            {
                boolean verifica=Interfaz_Login.metE.verificaCodigo(codigo);
                if(verifica==false)
                {
                    String insertar=Interfaz_Login.metE.InsertarFinal(nombre, codigo, ImagenCasa, ImagenVisita);

                    JOptionPane.showMessageDialog(null, insertar);
                    //
                    jTextField1.setText("");
                    jTextField2.setText("");
                    lblImagen1.setText("");
                    lblImagen2.setText("");
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"El codigo seleccionado se encuentra ocupado");
                }
            }
            else
            {
            JOptionPane.showMessageDialog(null,"Debe Seleccionar los Uniformes");
            }
            
        }
        catch (Exception e) 
        {
           JOptionPane.showMessageDialog(null,"Error al Ingresar los Datos");
        }
        
        
    }//GEN-LAST:event_jButton2_Insertar_FinalActionPerformed

    private void jButton1_Mostrar_informacion_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_Mostrar_informacion_ActionPerformed
        Imprimir();
    }//GEN-LAST:event_jButton1_Mostrar_informacion_ActionPerformed

    private void jButton1_Atras_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_Atras_ActionPerformed
        Interfaz_Login.principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1_Atras_ActionPerformed

    
    public void Imprimir()
    {
        ListModel.clear();
        if (Interfaz_Login.metE.inicio==Interfaz_Login.metE.inicio.sig)
        {
          ListModel.addElement("Nombre:  "+ Interfaz_Login.metE.inicio.nombre +"  Codigo:   "+ Interfaz_Login.metE.inicio.codigo);// muestra en ListModel el nombre y la edad del Cliente
        }
        else
        {
            Equipos temp = Interfaz_Login.metE.inicio;
            Equipos aux = Interfaz_Login.metE.inicio;
            while(aux.sig != temp)
            {
                ListModel.addElement("Nombre: "+aux.nombre +"  Codigo:  "+ aux.codigo);// muestra en ListModel el nombre y la edad del Cliente
                aux=aux.sig;
            }
            ListModel.addElement("Nombre: "+aux.nombre +"  Codigo:  "+ aux.codigo);
        }
        jList1.setModel(ListModel);    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Equipos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_Atras_;
    private javax.swing.JButton jButton1_Insertar_Inicio;
    private javax.swing.JButton jButton1_Mostrar_informacion_;
    private javax.swing.JButton jButton1_Uniforme_Casa_;
    private javax.swing.JButton jButton1_Uniforme_Visita;
    private javax.swing.JButton jButton2_Insertar_Final;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblImagen1;
    private javax.swing.JLabel lblImagen2;
    // End of variables declaration//GEN-END:variables
}
