/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graficos;
import java.io.File;
import javax.swing.*;
import Entidades.*;
import Metodos.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Oscar
 */
public class Interfaz_Equipos extends javax.swing.JFrame {
    
    DefaultTableModel equipos;
    
    JFileChooser seleccionado = new JFileChooser();
    File archivo;
    byte[] bytesImg;
    
    Gestion_de_Imagenes gestionCasa = new Gestion_de_Imagenes();
    Gestion_de_Imagenes gestionVisita = new Gestion_de_Imagenes();
    
    /**
     * Creates new form JFGestionA
     */
    public Interfaz_Equipos() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1_Insertar_Inicio = new javax.swing.JButton();
        jButton2_Insertar_Final = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton1_Atras_ = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador crea Equipo");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Agregar Equipo");

        jLabel2.setText("Nombre");

        jLabel3.setText("Codigo");

        jButton1_Insertar_Inicio.setText("Agragrgar al Inicio");
        jButton1_Insertar_Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_Insertar_InicioActionPerformed(evt);
            }
        });

        jButton2_Insertar_Final.setText("Agrgar al Final");
        jButton2_Insertar_Final.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_Insertar_FinalActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 153));
        jLabel8.setText("Mostrar ");

        jButton1_Atras_.setText("Atras");
        jButton1_Atras_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_Atras_ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1_Insertar_Inicio)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2_Insertar_Final))
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(341, 341, 341)
                        .addComponent(jButton1_Atras_))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1_Insertar_Inicio)
                            .addComponent(jButton2_Insertar_Final)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jButton1_Atras_)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton1_Insertar_InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_Insertar_InicioActionPerformed
        try 
        {
            
            String nombre=jTextField1.getText();
            int    codigo=Integer.parseInt(jTextField2.getText());
            
 
            boolean verifica=Interfaz_Login.metE.verificaCodigo(codigo);
            if(verifica==false)
            {
                    String insertar=Interfaz_Login.metE.InsertarInicio(nombre, codigo);

                    JOptionPane.showMessageDialog(null, insertar);
                    Imprimir();
                    //limpiar
                    jTextField1.setText("");
                    jTextField2.setText("");
            }
            else
            {
                JOptionPane.showMessageDialog(null,"El codigo seleccionado se encuentra ocupado");
            }
            
         
            
        }
        catch (Exception e) 
        {
           JOptionPane.showMessageDialog(null,"Error al Ingresar los Datos");
        }
    }//GEN-LAST:event_jButton1_Insertar_InicioActionPerformed

    private void jButton2_Insertar_FinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_Insertar_FinalActionPerformed
      try 
        {
            
            String nombre=jTextField1.getText();
            int    codigo=Integer.parseInt(jTextField2.getText());
            
        
            boolean verifica=Interfaz_Login.metE.verificaCodigo(codigo);
            if(verifica==false)
            {
                    String insertar=Interfaz_Login.metE.InsertarFinal(nombre, codigo);

                    JOptionPane.showMessageDialog(null, insertar);
                    Imprimir();
                    //
                    jTextField1.setText("");
                    jTextField2.setText("");
            }
            else
            {
                    JOptionPane.showMessageDialog(null,"El codigo seleccionado se encuentra ocupado");
            }
         
            
        }
        catch (Exception e) 
        {
           JOptionPane.showMessageDialog(null,"Error al Ingresar los Datos");
        }
        
        
    }//GEN-LAST:event_jButton2_Insertar_FinalActionPerformed

    private void jButton1_Atras_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_Atras_ActionPerformed
        Interfaz_Login.principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1_Atras_ActionPerformed

    
    public void Imprimir()
    {
        //Tabla para Equipos
        String titulo3[]={"Nombre","Codigo"};
        String datos3[][]={};
        equipos=new DefaultTableModel(datos3,titulo3);
        jTable1.setModel(equipos);
        
        if (Interfaz_Login.metE.inicio==Interfaz_Login.metE.inicio.sig)
        {
            //Tabla para Equipos
          Object datos[]={Interfaz_Login.metE.inicio.nombre,Interfaz_Login.metE.inicio.codigo};
          equipos.addRow(datos);
        }
        else
        {
            Equipos temp = Interfaz_Login.metE.inicio;
            Equipos aux = Interfaz_Login.metE.inicio;
            while(aux.sig != temp)
            {
               //Tabla para Equipos
                Object datos[]={aux.nombre,aux.codigo};
                equipos.addRow(datos);
                aux=aux.sig;
            }
            //Tabla para Equipos
            Object datos[]={aux.nombre,aux.codigo};
            equipos.addRow(datos);
        }   
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Equipos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_Atras_;
    private javax.swing.JButton jButton1_Insertar_Inicio;
    private javax.swing.JButton jButton2_Insertar_Final;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
