/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graficos;

import Entidades.Entrenadores;
import Metodos.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Admi
 */
public class Interfaz_Login extends javax.swing.JFrame {

    
    //interfaces
    public static Interfaz_Info                  info  = new Interfaz_Info();
    public static Interfaz_MenuPrincipal         principal  = new Interfaz_MenuPrincipal();
    public static Interfaz_Entrenador            entrenador = new Interfaz_Entrenador();
    public static Interfaz_Jugadores             jugadores  = new Interfaz_Jugadores();
    public static Interfaz_Torneo                torneo     = new Interfaz_Torneo();
    public static Interfaz_Equipos               equipos    = new Interfaz_Equipos();
    public static Interfaz_Enlaces               enlaces   =  new Interfaz_Enlaces();
    public static Interfaz_Estadio               estadio   =  new Interfaz_Estadio();
    public static Interfaz_Usuario_Entrenador      userEntrenador  =  new Interfaz_Usuario_Entrenador();
    
    //metodos
    public static Metodos_Enlace_Torneo_Equipo     metET =  new Metodos_Enlace_Torneo_Equipo();
    public static MetodosEquipos                   metE  =  new MetodosEquipos();
    public static MetodosEntrenador                metEn =  new MetodosEntrenador(); 
    public static MetodosJugadores                 metJ  =  new MetodosJugadores();
    public static MetodosTorneo                    metT  =  new MetodosTorneo();
    public static Metodos_Enlace_Entrenador_Equipo metEnE  =  new Metodos_Enlace_Entrenador_Equipo();
    public static MetodosLogin                     metL  =  new MetodosLogin();
    
    
    
    
    
    
    /**
     * Creates new form Login
     */
    public Interfaz_Login(MetodosLogin metodos) {  
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreUsuarioTxt = new javax.swing.JTextField();
        contraseñaTxt = new javax.swing.JTextField();
        IngresarBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log In");
        setPreferredSize(new java.awt.Dimension(583, 360));

        jLabel1.setText("Nombre de usuario:");

        jLabel2.setText("Contraseña:");

        IngresarBtn.setText("Ingresar");
        IngresarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IngresarBtnMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setText("Log In");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreUsuarioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contraseñaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IngresarBtn))))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombreUsuarioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(contraseñaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IngresarBtn)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //QUEMA DE DATOS
    //Datos para entrenador
    String Enuevo1=Interfaz_Login.metEn.InsertarInicio("Jorge Luis Pinto ",203040);
    String Enuevo2=Interfaz_Login.metEn.InsertarInicio("Andrey Amdor ",213344);
    String Enuevo3=Interfaz_Login.metEn.InsertarInicio("Oscar Ramirez ",223444);
    String Enuevo4=Interfaz_Login.metEn.InsertarInicio("Bob Marley",233444);
    String Enuevo5=Interfaz_Login.metEn.InsertarInicio("Rammstein",24);
    String Enuevo6=Interfaz_Login.metEn.InsertarInicio("Skiller ",253444);
    String Enuevo7=Interfaz_Login.metEn.InsertarInicio("Red Hot Chili Peppers ",233444);
    //Datos para jugadores
    String Jnuevo1=Interfaz_Login.metJ.InsertarInicio("Keylor"   , 0,10,10,10,10,"Portero");
    String Jnuevo2=Interfaz_Login.metJ.InsertarInicio("Gamboa"   , 1,5,9,2,9,"Defensa");
    String Jnuevo3=Interfaz_Login.metJ.InsertarInicio("Acosta"   , 2,8,3,8,1,"Defensa");
    String Jnuevo4=Interfaz_Login.metJ.InsertarInicio("Ganzalesz", 3,7,3,4,1,"Defensa");
    String Jnuevo5=Interfaz_Login.metJ.InsertarInicio("Umaña"    , 4,5,3,8,7,"Defensa");
    String Jnuevo6=Interfaz_Login.metJ.InsertarInicio("Cubero"   , 5,8,6,8,1,"Medio Campo");
    String Jnuevo7=Interfaz_Login.metJ.InsertarInicio("Borges"   , 6,8,10,8,9,"Medio Campo");
    String Jnuevo8=Interfaz_Login.metJ.InsertarInicio("Tejeda"   , 7,2,1,8,9,"Medio Campo");
    String Jnuevo9=Interfaz_Login.metJ.InsertarInicio("Bolaños"   , 8,4,1,2,9,"Medio Campo");
    String Jnuevo10=Interfaz_Login.metJ.InsertarInicio("Campbell" , 9,2,9,4,9,"Delantero");
    String Jnuevo11=Interfaz_Login.metJ.InsertarInicio("B.Ruiz"   , 10,10,10,8,9,"Delantero");
    //Datos para equipos
    String EQnuevo1=Interfaz_Login.metE.InsertarInicio("Costa Rica", 0, null, null);
    String EQnuevo2=Interfaz_Login.metE.InsertarInicio("Estados Unidos", 1, null, null);
    String EQnuevo3=Interfaz_Login.metE.InsertarInicio("Honduras", 2, null, null);
    String EQnuevo4=Interfaz_Login.metE.InsertarInicio("Mexico", 3, null, null);
    //Datos para torneo
    String Tnuevo1=Interfaz_Login.metT.insertarInicio("Mundial 2014");
    //Datos de enlace equipo/torneo
    //String Ennuevo1=Interfaz_Login.metET.insertarInicioEnlaceTorneoEquipo("Mundial 2014",Interfaz_Login.metT.insertarInicio("Mundial 2014"),Tnuevo1,Interfaz_Login.metE.InsertarInicio("Costa Rica", 0, null, null));
    
    private void IngresarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresarBtnMouseClicked
        // TODO add your handling code here:
        String nombreUsuario = nombreUsuarioTxt.getText();
        String contraseña = contraseñaTxt.getText();
        int contraEntrenadores=Integer.parseInt(contraseñaTxt.getText());
       
        
        if (nombreUsuario.equals("Fifa") && contraseña.equals("123"))
        {
            this.dispose();
            new Interfaz_MenuPrincipal().setVisible(true);
        }
        else
        {
            int bandera=0;
            for(Entrenadores i:Interfaz_Login.metL.entrenadores){
                if(i.getNombre().equals(nombreUsuario) && i.getId()==contraEntrenadores)
                {
                    bandera=1;
                    this.dispose();
                    new Interfaz_Usuario_Entrenador().setVisible(true);  
                }
            }
            if(bandera==0)
            {
            JOptionPane.showMessageDialog(null,"Incorrecto");
            }
  
        }
        
        
    }//GEN-LAST:event_IngresarBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Login(new MetodosLogin()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IngresarBtn;
    private javax.swing.JTextField contraseñaTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nombreUsuarioTxt;
    // End of variables declaration//GEN-END:variables
}
