/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graficos;

import Entidades.Equipos;
import Metodos.MetodosEntrenador;
import Metodos.MetodosEquipos;
import Metodos.MetodosJugadores;
import Metodos.MetodosTorneo;
import Metodos.Metodos_Enlace_Torneo_Equipo;

/**
 *
 * @author Usuario
 */
public class Interfaz_MenuPrincipal extends javax.swing.JFrame {
    
    
   
    
   
    
    /**
     * Creates new form Interfaz_MenuPrincipal
     */
    public Interfaz_MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemAgregarEntrenador = new javax.swing.JMenuItem();
        jMenuItemAgregarJugador = new javax.swing.JMenuItem();
        jMenuItemAgregarEstadio = new javax.swing.JMenuItem();
        jMenuItemAgregarTorneo = new javax.swing.JMenuItem();
        jMenuItemAgregarEquipo = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");

        jMenu2.setText("Agregar");

        jMenuItemAgregarEntrenador.setText("Entrenador");
        jMenuItemAgregarEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgregarEntrenadorActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemAgregarEntrenador);

        jMenuItemAgregarJugador.setText("Jugador");
        jMenuItemAgregarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgregarJugadorActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemAgregarJugador);

        jMenuItemAgregarEstadio.setText("Estadio");
        jMenuItemAgregarEstadio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemAgregarEstadioMouseClicked(evt);
            }
        });
        jMenuItemAgregarEstadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgregarEstadioActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemAgregarEstadio);

        jMenuItemAgregarTorneo.setText("Torneo");
        jMenuItemAgregarTorneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgregarTorneoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemAgregarTorneo);

        jMenuItemAgregarEquipo.setText("Equipo");
        jMenuItemAgregarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgregarEquipoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemAgregarEquipo);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Enlaces");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu3.setText("Jugador");
        jMenuBar1.add(jMenu3);

        jMenu5.setText("Estadio");
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Torneo");
        jMenuBar1.add(jMenu6);

        jMenu7.setText("Salir");
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 583, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jMenuItemAgregarEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgregarEntrenadorActionPerformed
        // TODO add your handling code here:
        Interfaz_Login.entrenador.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemAgregarEntrenadorActionPerformed

    private void jMenuItemAgregarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgregarJugadorActionPerformed
        // TODO add your handling code here:
        Interfaz_Login.jugadores.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemAgregarJugadorActionPerformed

    private void jMenuItemAgregarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgregarEquipoActionPerformed
        // TODO add your handling code here:
        Interfaz_Login.equipos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemAgregarEquipoActionPerformed

    private void jMenuItemAgregarTorneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgregarTorneoActionPerformed
        Interfaz_Login.torneo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemAgregarTorneoActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        Interfaz_Login.enlaces.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenuItemAgregarEstadioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemAgregarEstadioMouseClicked
       Interfaz_Login.estadio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemAgregarEstadioMouseClicked

    private void jMenuItemAgregarEstadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgregarEstadioActionPerformed
        Interfaz_Login.estadio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemAgregarEstadioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAgregarEntrenador;
    private javax.swing.JMenuItem jMenuItemAgregarEquipo;
    private javax.swing.JMenuItem jMenuItemAgregarEstadio;
    private javax.swing.JMenuItem jMenuItemAgregarJugador;
    private javax.swing.JMenuItem jMenuItemAgregarTorneo;
    // End of variables declaration//GEN-END:variables
}
