/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graficos;
import java.io.File;
import javax.swing.*;
import Entidades.*;
import Metodos.*;
/**
 *
 * @author Oscar
 */
public class Interfaz_Estadio extends javax.swing.JFrame {
    
    JFileChooser seleccionado = new JFileChooser();
    File archivo;
    byte[] bytesImg;
    
    Gestion_de_Imagenes gestionCasa = new Gestion_de_Imagenes();
    Gestion_de_Imagenes gestionVisita = new Gestion_de_Imagenes();
    
    MetodosEquipos met =new MetodosEquipos();
    DefaultListModel <String> ListModel = new DefaultListModel <>();// esto es para poder usar la jlist1
    /**
     * Creates new form JFGestionA
     */
    public Interfaz_Estadio() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1_Uniforme_Visita = new javax.swing.JButton();
        lblImagen2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1_Insertar_Inicio = new javax.swing.JButton();
        jButton2_Insertar_Final = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador crea Equipo");

        jLabel9.setText("Capacidad Maxima");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Agregar Estadio");

        jLabel2.setText("Nombre");

        jLabel3.setText("Ubicacion");

        jLabel5.setText("Foto de Estadio");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setText("Foto del Estadio");

        jButton1_Uniforme_Visita.setText("Seleccionar");
        jButton1_Uniforme_Visita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_Uniforme_VisitaActionPerformed(evt);
            }
        });

        lblImagen2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1_Insertar_Inicio.setText("Agragrgar al Inicio");
        jButton1_Insertar_Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_Insertar_InicioActionPerformed(evt);
            }
        });

        jButton2_Insertar_Final.setText("Agrgar al Final");
        jButton2_Insertar_Final.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_Insertar_FinalActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 153));
        jLabel8.setText("Mostrar ");

        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1_Uniforme_Visita))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1_Insertar_Inicio)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2_Insertar_Final))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(42, 42, 42)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                .addComponent(jTextField2)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblImagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(155, 155, 155))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jButton1_Uniforme_Visita)))
                    .addComponent(lblImagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1_Insertar_Inicio)
                            .addComponent(jButton2_Insertar_Final)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_Uniforme_VisitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_Uniforme_VisitaActionPerformed
        if(seleccionado.showDialog(null, "ABRIR ARCHIVO") == JFileChooser.APPROVE_OPTION){
            archivo = seleccionado.getSelectedFile();
            
            if(archivo.getName().endsWith("jpg")||archivo.getName().endsWith("png")||archivo.getName().endsWith("gif"))
            {
                bytesImg = gestionVisita.AbrirAImagen(archivo);
                lblImagen2.setIcon(new ImageIcon(bytesImg));
              
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Por favor seleccione un archivo de texto o de imagen.");
            }
        }
    }//GEN-LAST:event_jButton1_Uniforme_VisitaActionPerformed

    private void jButton1_Insertar_InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_Insertar_InicioActionPerformed
        try 
        {
            
            String nombre=jTextField1.getText();
            int    codigo=Integer.parseInt(jTextField2.getText());
            
            ImageIcon ImagenCasa=(ImageIcon) lblImagen1.getIcon();
            ImageIcon ImagenVisita=(ImageIcon) lblImagen2.getIcon();
            
            if (ImagenCasa != null || ImagenVisita != null)
            {
                boolean verifica=met.verificaCodigo(codigo);
                if(verifica==false)
                {
                    String insertar=met.InsertarInicio(nombre, codigo, ImagenCasa, ImagenVisita);

                    JOptionPane.showMessageDialog(null, insertar);
                    Imprimir();
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"El codigo seleccionado se encuentra ocupado");
                }
            }
            else
            {
            JOptionPane.showMessageDialog(null,"Debe Seleccionar los Uniformes");
            }
            
        }
        catch (Exception e) 
        {
           JOptionPane.showMessageDialog(null,"Error al Ingresar los Datos");
        }
    }//GEN-LAST:event_jButton1_Insertar_InicioActionPerformed

    private void jButton2_Insertar_FinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_Insertar_FinalActionPerformed
      try 
        {
            
            String nombre=jTextField1.getText();
            int    codigo=Integer.parseInt(jTextField2.getText());
            
            ImageIcon ImagenCasa=(ImageIcon) lblImagen1.getIcon();
            ImageIcon ImagenVisita=(ImageIcon) lblImagen2.getIcon();
            
            if (ImagenCasa != null || ImagenVisita != null)
            {
                boolean verifica=met.verificaCodigo(codigo);
                if(verifica==false)
                {
                    String insertar=met.InsertarFinal(nombre, codigo, ImagenCasa, ImagenVisita);

                    JOptionPane.showMessageDialog(null, insertar);
                    Imprimir();
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"El codigo seleccionado se encuentra ocupado");
                }
            }
            else
            {
            JOptionPane.showMessageDialog(null,"Debe Seleccionar los Uniformes");
            }
            
        }
        catch (Exception e) 
        {
           JOptionPane.showMessageDialog(null,"Error al Ingresar los Datos");
        }
        
        
    }//GEN-LAST:event_jButton2_Insertar_FinalActionPerformed

    
    public void Imprimir()
    {
        ListModel.clear();
        if (met.inicio==met.inicio.sig)
        {
          ListModel.addElement("Nombre:  "+ met.inicio.nombre +"  Codigo:   "+ met.inicio.codigo);// muestra en ListModel el nombre y la edad del Cliente
        }
        else
        {
            Equipos temp = met.inicio;
            Equipos aux = met.inicio;
            while(aux.sig != temp)
            {
                ListModel.addElement("Nombre: "+aux.nombre +"  Codigo:  "+ aux.codigo);// muestra en ListModel el nombre y la edad del Cliente
                System.out.println(aux.nombre);
                aux=aux.sig;
            }
            ListModel.addElement("Nombre: "+aux.nombre +"  Codigo:  "+ aux.codigo);
        }
        jList1.setModel(ListModel);    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Estadio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Estadio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Estadio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Estadio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Estadio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_Insertar_Inicio;
    private javax.swing.JButton jButton1_Uniforme_Visita;
    private javax.swing.JButton jButton2_Insertar_Final;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblImagen2;
    // End of variables declaration//GEN-END:variables
}
