/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graficos;

import Entidades.Enlace_Torneo_Euipos;
import Entidades.Equipos;
import Entidades.Torneos;
import Metodos.MetodosEquipos;
import Metodos.MetodosTorneo;
import Metodos.Metodos_Enlace_Torneo_Equipo;
import javax.swing.JOptionPane;
import Graficos.Interfaz_MenuPrincipal;
import javax.swing.DefaultListModel;

/**
 *
 * @author Usuario
 */
public class Interfaz_Enlaces extends javax.swing.JFrame {

    DefaultListModel <String> ListModelTorneo = new DefaultListModel <>();
    
    /**
     * Creates new form Interfaz_Enlaces
     */
    
    public Interfaz_Enlaces() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1_Enlace_Equipo_Torneo_ = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4_Imprmir_ = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Enlaces");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Enlazar Equipo a Torneo");

        jLabel2.setText("Nombre del Torneo");

        jLabel3.setText("Nombre del Equipo");

        jButton1_Enlace_Equipo_Torneo_.setText("Enlazar");
        jButton1_Enlace_Equipo_Torneo_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_Enlace_Equipo_Torneo_ActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre del Entrnador");

        jLabel5.setText("Nombre del Equipo");

        jButton2.setText("Enlazar");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("Enlazar Equipo a Torneo");

        jButton3.setText("Atras");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4_Imprmir_.setText("Mostrar");
        jButton4_Imprmir_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_Imprmir_ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton1_Enlace_Equipo_Torneo_))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4_Imprmir_, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1_Enlace_Equipo_Torneo_)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addContainerGap(43, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4_Imprmir_)
                        .addGap(28, 28, 28))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 
    
    private void jButton1_Enlace_Equipo_Torneo_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_Enlace_Equipo_Torneo_ActionPerformed
        try
        {
           //Equipos algo=principal.metE.inicio;
            
            String nombreTorneo=jTextField1.getText();
            String nombreEquipo=jTextField2.getText();
           
            //boolean very=VerificaTorneo(nombreTorneo);
            Torneos veri1=VerificaTorneo(nombreTorneo);
            Equipos veri2=VerificaEquipo(nombreEquipo);
            
            String insertado=Interfaz_Login.metET.insertarInicioEnlaceTorneoEquipo(nombreTorneo, nombreEquipo,veri2,veri1);
            imprimirSub2();
            JOptionPane.showMessageDialog(null,insertado);
        }
        catch(Exception e )
        {
            JOptionPane.showMessageDialog(null,"Error en los datos");
        }
        
    }//GEN-LAST:event_jButton1_Enlace_Equipo_Torneo_ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Interfaz_Login.principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4_Imprmir_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_Imprmir_ActionPerformed
      imprimirSub2();
    }//GEN-LAST:event_jButton4_Imprmir_ActionPerformed

    public Torneos VerificaTorneo(String nombreTorneo)
    {
        if(Interfaz_Login.metT.inicio == null )
        {
            return null;
        }
        Torneos aux=Interfaz_Login.metT.inicio;
        while(aux != null)
        {
            if(aux.nombre.equals(nombreTorneo))
            {
               return aux;
            }
            aux=aux.sig;
        }
        return null;
    }
    
    public Equipos VerificaEquipo(String nombreEquipo)
    {
        if(Interfaz_Login.metT.inicio== null)
        {
            return null;
        }
       
        Equipos aux =Interfaz_Login.metE.inicio;
        
        while(aux != Interfaz_Login.metE.fin)
        {
            if(aux.nombre.equals(nombreEquipo))
            {
                return aux;
            }
            aux=aux.sig;
        }
        
        if(Interfaz_Login.metE.fin.nombre.equals(nombreEquipo))
        {
            return Interfaz_Login.metE.fin;
        }
        return null;
    }
    
    //fecha 04/04/17
    // por este metodo va a imprimir por cada torneo sus integrantes
    public void imprimirSub2()  
    {
        ListModelTorneo.clear();
        if (Interfaz_Login.metE.inicio==null)
        {
            JOptionPane.showMessageDialog(null, "Lista Vacia");
        }
        
        else
        {          
            Torneos torneo = Interfaz_Login.metT.inicio;    // entro a los Torneo
            while(  torneo != null)
            { 
              Equipos equipo = Interfaz_Login.metE.inicio;
              if(equipo==null)
              {
                JOptionPane.showMessageDialog(null,"Lista de equipos esta vacia");
                break;
              }
              else
              {
 
                while(equipo != Interfaz_Login.metE.fin)
                {
                    Enlace_Torneo_Euipos  enlace =equipo.sigSub;
                    while(enlace != null)
                    {
                        if(enlace.sigTorneo==torneo)
                        {
                            ListModelTorneo.addElement("Torneo---> "+torneo.nombre +"  "+"Equipo----> "+equipo.nombre);
                            break;
                        }

                    }
                    equipo=equipo.sig;
                }
                if(Interfaz_Login.metE.fin.sigSub.sigTorneo==torneo)
                {
                    ListModelTorneo.addElement("Torneo---> "+torneo.nombre +"  "+"Equipo----> "+equipo.nombre);
                    break;
                }
                
              }
              torneo=torneo.sig;
            }
            jList1.setModel(ListModelTorneo); 
        }
    }  
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Enlaces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Enlaces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Enlaces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Enlaces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Enlaces().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_Enlace_Equipo_Torneo_;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4_Imprmir_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
