/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graficos;

import Entidades.Enlace_Jugador_Equipo;
import Entidades.Equipos;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class Interfaz_Usuario_Entrenador_Compra_por_Traspaso extends javax.swing.JFrame {

    DefaultTableModel equipos;
    /**
     * Creates new form Interfaz_Usuario_Entrenador_Compra_por_Traspaso
     */
    public Interfaz_Usuario_Entrenador_Compra_por_Traspaso() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        _Comprar_ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Dinero Disponible");

        jLabel2.setText("Mi Equipo");

        jLabel3.setForeground(new java.awt.Color(0, 102, 0));
        jLabel3.setText("jLabel3");

        jLabel4.setForeground(new java.awt.Color(0, 102, 0));
        jLabel4.setText("jLabel4");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("Mi Equipo");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("En Venta");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Nombre del Jugador");

        jButton2.setText("Mostrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Mostrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        _Comprar_.setText("Comprar");
        _Comprar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _Comprar_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(_Comprar_, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(_Comprar_))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Interfaz_Login.userEntrenador.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        imprimirMiEquipo();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ImprimirJugadorXEquipo();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void _Comprar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__Comprar_ActionPerformed
        //try
        //{
            String nombreJugador=jTextField1.getText();
            
            String insertado=Interfaz_Login.metVenta.comprarVenta(nombreJugador);
            
            JOptionPane.showMessageDialog(null,insertado);
            
        //}
        //catch(Exception e)
        //{
        //    JOptionPane.showMessageDialog(null,"Error de datos");
        //}
    }//GEN-LAST:event__Comprar_ActionPerformed

    
    public void ImprimirJugadorXEquipo()
    {
      
        
        
        //Tabla para Equipos
        String titulo3[]={"Equipo","Jugador","Estado","Valor"};
        String datos3[][]={};
        equipos=new DefaultTableModel(datos3,titulo3);
        jTable1.setModel(equipos);
        
        if (Interfaz_Login.metE.inicio==Interfaz_Login.metE.inicio.sig)
        {
          //Tabla para Equipos
          if(Interfaz_Login.metE.inicio.sigSub1 != null)
          {
              
            Enlace_Jugador_Equipo  sub=Interfaz_Login.metE.inicio.sigSub1;
            while(sub != null) 
            { 
                if(sub.sigJugador.getEstado().equals("En Venta"))
                {
                    Object datos[]={Interfaz_Login.metE.inicio.nombre,Interfaz_Login.metE.inicio.sigSub1.sigJugador.getNombre(),Interfaz_Login.metE.inicio.sigSub1.sigJugador.getEstado(),Interfaz_Login.metE.inicio.sigSub1.sigJugador.getValor()};
                    equipos.addRow(datos);
                }
                sub=sub.sig;
            
            }
          }
        }
        else
        {
            Equipos temp = Interfaz_Login.metE.inicio;
            Equipos aux = Interfaz_Login.metE.inicio;
            
            while(aux.sig != temp)
            {
               //Tabla para Equipos
                if(aux.sigSub1 != null)
                {
                    Enlace_Jugador_Equipo  sub=aux.sigSub1;
                    while(sub != null) 
                    { 
                        if(sub.sigJugador.getEstado().equals("En Venta"))
                        {
                        Object datos[]={aux.nombre,sub.sigJugador.getNombre(),sub.sigJugador.getEstado(),sub.sigJugador.getValor()};
                        equipos.addRow(datos);
                        }
                        sub=sub.sig;
                    }
                }
                aux=aux.sig;
            }
            if(aux.sigSub1 != null)
            {
                Enlace_Jugador_Equipo  sub=aux.sigSub1;
                    while(sub != null) 
                    { 
                        if(sub.sigJugador.getEstado().equals("En Venta"))
                        {
                        Object datos[]={aux.nombre,sub.sigJugador.getNombre(),sub.sigJugador.getEstado(),sub.sigJugador.getValor()};
                        equipos.addRow(datos);        
                        }
                        sub=sub.sig;
                    }
            }
        }   
    }
    
    
    public void imprimirMiEquipo()
    {
        String nombreEquipo=Interfaz_Login.userEntrenador.jLabel4.getText();
        //Tabla para Equipos
        String titulo3[]={"Nombre","Jugador","Posicion"};
        String datos3[][]={};
        equipos=new DefaultTableModel(datos3,titulo3);
        jTable2.setModel(equipos);
        
        if (Interfaz_Login.metE.inicio==Interfaz_Login.metE.inicio.sig && Interfaz_Login.metE.inicio.nombre.equals(nombreEquipo) )
        {
          //Tabla para Equipos
          if(Interfaz_Login.metE.inicio.sigSub1 != null)
          {
              
            Enlace_Jugador_Equipo  sub=Interfaz_Login.metE.inicio.sigSub1;
            while(sub != null) 
            { 
            Object datos[]={Interfaz_Login.metE.inicio.nombre,Interfaz_Login.metE.inicio.sigSub1.sigJugador.getNombre(),Interfaz_Login.metE.inicio.sigSub1.sigJugador.getPosicion()};
            equipos.addRow(datos);
            sub=sub.sig;
            
            }
          }
        }
        else
        {
            Equipos temp = Interfaz_Login.metE.inicio;
            Equipos aux = Interfaz_Login.metE.inicio;
            
            while(aux.sig != temp)
            {
               //Tabla para Equipos
                if(aux.sigSub1 != null && aux.nombre.equals(nombreEquipo))
                {
                    Enlace_Jugador_Equipo  sub=aux.sigSub1;
                    while(sub != null) 
                    { 
                    Object datos[]={aux.nombre,sub.sigJugador.getNombre(),sub.sigJugador.getPosicion()};
                    equipos.addRow(datos);
                    sub=sub.sig;
                    }
                }
                aux=aux.sig;
            }
            if(aux.sigSub1 != null && aux.nombre.equals(nombreEquipo))
            {
                Enlace_Jugador_Equipo  sub=aux.sigSub1;
                    while(sub != null) 
                    { 
                    Object datos[]={aux.nombre,sub.sigJugador.getNombre(),sub.sigJugador.getPosicion()};
                    equipos.addRow(datos);
                    sub=sub.sig;
                    }
            }
        }   
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Usuario_Entrenador_Compra_por_Traspaso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Usuario_Entrenador_Compra_por_Traspaso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Usuario_Entrenador_Compra_por_Traspaso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Usuario_Entrenador_Compra_por_Traspaso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Usuario_Entrenador_Compra_por_Traspaso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _Comprar_;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
